# Generated by Django 4.2.1 on 2024-07-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_html', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.emailtemplate')),
            ],
        ),
    ]
