# Stage 1: Build the frontend application
FROM node:18 AS frontend

# Set the working directory for frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the working directory
COPY frontend/package*.json ./

# Install the frontend dependencies
RUN npm install

# Define the command to run the frontend development server
CMD ["npm", "run", "dev"]

# Stage 2: Build the backend application
FROM python:3.11 AS backend

# Ensure the output from Python is unbuffered (useful for logging)
ENV PYTHONUNBUFFERED=1

# Set the working directory for backend
WORKDIR /code

# Copy the backend requirements file to the working directory
COPY backend/requirements.txt .

# Install the backend dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Define the command to run the backend development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# Stage 3: Setup Nginx for serving the application
FROM nginx:alpine AS nginx

# Copy the Nginx configuration file to the container
COPY nginx.dev.conf /etc/nginx/nginx.conf
