# Development Dockerfile
FROM node:18 AS frontend
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
CMD ["npm", "run", "dev"]

FROM python:3.11 AS backend
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

FROM nginx:alpine AS nginx
COPY nginx.dev.conf /etc/nginx/nginx.conf