# Generated by Django 4.2.1 on 2024-07-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_opening_hours', models.BooleanField(default=False)),
                ('sync_menu', models.BooleanField(default=False)),
                ('sync_promotions', models.BooleanField(default=False)),
                ('sync_frequency', models.DurationField(null=True)),
                ('retry_attempts', models.IntegerField(default=3)),
                ('last_synced_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.apiintegration')),
            ],
        ),
    ]
