# Generated by Django 4.2.1 on 2024-07-15 05:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dietary Preference',
                'verbose_name_plural': 'Dietary Preferences',
            },
        ),
        migrations.CreateModel(
            name='DietaryPreferenceTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dietary Preference Translation',
                'verbose_name_plural': 'Dietary Preference Translations',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_in_buffet', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredients', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.foodcategory')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
            },
        ),
        migrations.CreateModel(
            name='FoodItemTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.fooditem')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.language')),
            ],
            options={
                'verbose_name': 'Food Item Translation',
                'verbose_name_plural': 'Food Item Translations',
            },
        ),
        migrations.CreateModel(
            name='FoodItemDietaryInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dietary_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dietarypreference')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.fooditem')),
            ],
            options={
                'verbose_name': 'Food Item Dietary Info',
                'verbose_name_plural': 'Food Item Dietary Info',
            },
        ),
        migrations.CreateModel(
            name='FoodCategoryTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.foodcategory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.language')),
            ],
            options={
                'verbose_name': 'Food Category Translation',
                'verbose_name_plural': 'Food Category Translations',
            },
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='menu_foodca_search__c0ed6e_gin'),
        ),
        migrations.AddField(
            model_name='dietarypreferencetranslation',
            name='dietary_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dietarypreference'),
        ),
        migrations.AddField(
            model_name='dietarypreferencetranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.language'),
        ),
        migrations.AlterUniqueTogether(
            name='fooditemtranslation',
            unique_together={('food_item', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='fooditemdietaryinfo',
            unique_together={('food_item', 'dietary_info')},
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['category'], name='menu_foodit_categor_a6431b_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_available'], name='menu_foodit_is_avai_f85550_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='menu_foodit_search__854653_gin'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['additional_info'], name='menu_foodit_additio_05c3ae_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='foodcategorytranslation',
            unique_together={('category', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='dietarypreferencetranslation',
            unique_together={('language', 'dietary_preference')},
        ),
    ]
