name: Build and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check if secrets are set
        run: |
          missing_secrets=()
          for secret in DOCKERHUB_USERNAME DOCKERHUB_TOKEN POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD POSTGRES_HOST POSTGRES_PORT DJANGO_SECRET_KEY DJANGO_DEBUG DJANGO_SUPERUSER_USERNAME DJANGO_SUPERUSER_EMAIL DJANGO_SUPERUSER_PASSWORD RENDER_DEPLOY_HOOK
          do
            if [ -z "${{ secrets[secret] }}" ]; then
              missing_secrets+=($secret)
            fi
          done
          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "Error: The following secrets are not set: ${missing_secrets[*]}"
            exit 1
          fi
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fryday:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fryday:${{ github.sha }}
          build-args: |
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}
            DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
            DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
            DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fryday:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fryday:buildcache,mode=max

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$deploy_url" ]; then
            echo "Error: RENDER_DEPLOY_HOOK is not set"
            exit 1
          fi
          curl -X POST $deploy_url